# Generated by Django 5.0 on 2025-11-11 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('organizations', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_users', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=50, verbose_name='User Role'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['organization', 'is_active'], name='telegram_us_organiz_21b54f_idx'),
        ),
    ]
