# Generated by Django 5.0 on 2025-11-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
        ('organizations', '0002_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the bot (3-100 characters)', max_length=100, verbose_name='Bot Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of bot purpose', max_length=500, null=True, verbose_name='Description')),
                ('telegram_token', models.CharField(help_text='Bot token from @BotFather', max_length=255, verbose_name='Telegram Bot Token')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the bot is currently active', verbose_name='Is Active')),
                ('total_conversations', models.IntegerField(default=0)),
                ('total_documents', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
                'db_table': 'bots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='bots_organiz_470b3b_idx')],
                'unique_together': {('organization', 'telegram_token')},
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name (3-200 characters)', max_length=200, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, help_text='Optional template description', max_length=1000, null=True, verbose_name='Description')),
                ('content', models.TextField(help_text='Template content with placeholders (10-10000 characters)', verbose_name='Template Content')),
                ('category', models.CharField(choices=[('appeal', 'Appeal (Заявление)'), ('complaint', 'Complaint (Жалоба)'), ('request', 'Request (Ходатайство)'), ('statement', 'Statement (Объяснение)'), ('other', 'Other (Другое)')], default='appeal', max_length=50, verbose_name='Category')),
                ('is_public', models.BooleanField(default=False, help_text='Share template with all organizations', verbose_name='Is Public')),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'category'], name='templates_organiz_881d27_idx'), models.Index(fields=['is_public'], name='templates_is_publ_c33849_idx')],
            },
        ),
    ]
