# Generated by Django 5.0 on 2025-11-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_refactor_for_bot_factory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='knowledgebasefile',
            name='templates_organiz_881d27_idx',
        ),
        migrations.RemoveIndex(
            model_name='knowledgebasefile',
            name='templates_is_publ_c33849_idx',
        ),
        migrations.RenameIndex(
            model_name='knowledgebasefile',
            new_name='knowledge_b_bot_id_c36653_idx',
            old_name='knowledge_b_bot_id_status_idx',
        ),
        migrations.AlterField(
            model_name='bot',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Main instructions/role for the bot (e.g., "You are a sales assistant...")', null=True, verbose_name='System Prompt'),
        ),
    ]
