# Generated by Django 5.0 on 2025-11-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_knowledgebasefile_templates_organiz_881d27_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebasefile',
            name='chunk_count',
            field=models.IntegerField(default=0, help_text='Number of text chunks with embeddings', verbose_name='Number of chunks'),
        ),
        migrations.AddField(
            model_name='knowledgebasefile',
            name='embeddings',
            field=models.JSONField(blank=True, help_text='Vector embeddings for semantic search', null=True, verbose_name='Text Embeddings'),
        ),
    ]
