# Generated by Django 5.0 on 2025-11-12 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_knowledgebasefile_chunk_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage this bot', related_name='assigned_bots', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Users'),
        ),
        migrations.AddField(
            model_name='bot',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this bot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bots', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
