# Generated by Django 5.0 on 2025-11-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_user_bot_relationships'),
        ('organizations', '0002_alter_organization_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('content', models.TextField(help_text='Template text content', verbose_name='Template Content')),
                ('category', models.CharField(help_text='Template category for organization', max_length=100, verbose_name='Category')),
                ('is_public', models.BooleanField(default=False, help_text='Whether template is public or private to organization', verbose_name='Is Public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'db_table': 'templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'category'], name='templates_organiz_881d27_idx')],
            },
        ),
    ]
