# Generated by Django 5.0 on 2025-11-11 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=50, verbose_name='Subscription Plan')),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], default='active', max_length=50, verbose_name='Subscription Status')),
                ('bots_quota', models.IntegerField(default=1, verbose_name='Bots Limit')),
                ('bots_used', models.IntegerField(default=0, verbose_name='Bots Used')),
                ('documents_quota', models.IntegerField(default=10, verbose_name='Monthly Documents Limit')),
                ('documents_used', models.IntegerField(default=0, verbose_name='Documents Used This Month')),
                ('api_calls_quota', models.IntegerField(default=0, verbose_name='Monthly API Calls Limit')),
                ('api_calls_used', models.IntegerField(default=0, verbose_name='API Calls Used This Month')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Subscription ID')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Custom settings for branding, AI preferences, etc.', verbose_name='Organization Settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'), models.Index(fields=['plan'], name='organizatio_plan_b94df1_idx'), models.Index(fields=['subscription_status'], name='organizatio_subscri_72b760_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Key Name')),
                ('prefix', models.CharField(editable=False, max_length=20, verbose_name='Key Prefix')),
                ('key_hash', models.CharField(editable=False, max_length=255, verbose_name='Key Hash')),
                ('permissions', models.JSONField(default=dict, help_text='Allowed actions: generate_document, manage_bots, etc.', verbose_name='Permissions')),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='api_keys_organiz_70e45b_idx'), models.Index(fields=['prefix'], name='api_keys_prefix_5bc339_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete')], max_length=50)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='subscriptio_organiz_4f7e3a_idx'), models.Index(fields=['stripe_subscription_id'], name='subscriptio_stripe__aa726e_idx')],
            },
        ),
    ]
